.PHONY all:
all:
	gcc -Wall -D PART1 fs.c -o diskinfo
	gcc -Wall -D PART2 fs.c -o disklist
	gcc -Wall -D PART3 fs.c -o diskget
	gcc -Wall -D PART4 fs.c -o diskput

.PHONY clean:
clean:
	-rm diskinfo disklist diskget diskput